### ISSUE TITLE
Error on current develop core and themes

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1066]
Viewing public side of site pages returns the following error:

```
Zend\Navigation\Exception\BadMethodCallException
Bad method call: Unknown method Zend\Navigation\Navigation::menu

Details:

exception 'Zend\Navigation\Exception\BadMethodCallException' with message 'Bad method call: Unknown method Zend\Navigation\Navigation::menu' in /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-navigation/src/AbstractContainer.php:375
Stack trace:
#0 [internal function]: Zend\Navigation\AbstractContainer->__call('menu', Array)
#1 [internal function]: Zend\Navigation\Navigation->menu()
#2 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/Helper/Navigation/AbstractHelper.php(134): call_user_func_array(Array, Array)
#3 /websites/omekadev/home/www/mebrett/testomekas/application/view/omeka/site/page/show.phtml(19): Zend\View\Helper\Navigation\AbstractHelper->__call('menu', Array)
#4 /websites/omekadev/home/www/mebrett/testomekas/application/view/omeka/site/page/show.phtml(19): Zend\View\Helper\Navigation\Menu->menu()
#5 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(505): include('/websites/omeka...')
#6 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#7 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#8 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#9 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#10 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#11 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#12 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#13 /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#14 /websites/omekadev/home/www/mebrett/testomekas/index.php(21): Zend\Mvc\Application->run()
#15 {main}
```

[example](http://dev.omeka.org/mebrett/testomekas/s/austen/page/life)

**Comment by mebrett** [comment]
Persists across all themes

**Comment by zerocrates** [comment]
bleh.

This is an expected issue in some ways because it comes from a change we just made to make the nav bar just be the "menu" helper directly, but the page/show view here wants to use both the breadcrumb and menu helpers... so we'll have to change something there.

**Comment by patrickmj** [comment]
This isn't the thing I hit a few days ago? Looks very similar.

**Comment by zerocrates** [comment]
It's similar but different.

**Comment by patrickmj** [comment]
Ah, yes. nested navigation reproduces it.

**Comment by zerocrates** [comment]
You'll have to pull all themes (again).
