### ISSUE TITLE
Cannot batch create resource templates

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1072]
When batch creating resource templates I get the following error:

```
PHP Fatal error:  Uncaught Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Omeka\Entity\ResourceTemplateProperty#resourceTemplate' that was not configured to cascade persist operations for entity: Omeka\Entity\ResourceTemplate@00000000452338c80000000047df6d44. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Omeka\Entity\ResourceTemplate#__toString()' to get a clue. in /mnt/1TB/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Stack trace:
#0 /mnt/1TB/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(852): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Omeka\Entity\ResourceTemplate))
#1 /mnt/1TB/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(740): Doctrine\ORM\U in /mnt/1TB/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php on line 92
```

**Comment by zerocrates** [comment]
Hmmm.... probably missing cascade detach

**Comment by zerocrates** [comment]
Specifically, needing `cascade={"detach"}` on https://github.com/omeka/omeka-s/blob/develop/application/src/Entity/ResourceTemplateProperty.php#L30

would be my guess

**Comment by zerocrates** [comment]
Whoops, I mean, adding detach here: https://github.com/omeka/omeka-s/blob/develop/application/src/Entity/ResourceTemplate.php#L40
