### ISSUE TITLE
Address ACL issues across module access and events

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1087]
Following up on https://github.com/omeka-s-modules/Mapping/issues/36, I tried to add an item as Editor (without any Mapping data). It collided with DspaceConnector.

It seems like some interaction between the core and module ACL has a problem, either in a pattern in modules, or in how it gets looped into core.

```
Omeka\Api\Exception\PermissionDeniedException
Permission denied for the current user to search the DspaceConnector\Api\Adapter\DspaceItemAdapter resource.

Details:

Omeka\Api\Exception\PermissionDeniedException: Permission denied for the current user to search the DspaceConnector\Api\Adapter\DspaceItemAdapter resource. in /var/www/html/omekas/application/src/Api/Manager.php:208
Stack trace:
#0 /var/www/html/omekas/application/src/Api/Manager.php(59): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#1 /var/www/html/omekas/modules/DspaceConnector/Module.php(63): Omeka\Api\Manager->search('dspace_items', Array)
#2 /var/www/html/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): DspaceConnector\Module->showSource(Object(Zend\EventManager\Event))
#3 /var/www/html/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#4 /var/www/html/omekas/application/src/View/Helper/Trigger.php(61): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#5 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.show.after')
#6 /var/www/html/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#7 /var/www/html/omekas/application/view/omeka/admin/item/show.phtml(85): Zend\View\Renderer\PhpRenderer->__call('trigger', Array)
#8 /var/www/html/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/o...')
#9 /var/www/html/omekas/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render()
#10 /var/www/html/omekas/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#11 /var/www/html/omekas/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#12 /var/www/html/omekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#13 /var/www/html/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#14 /var/www/html/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/omekas/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/omekas/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#17 /var/www/html/omekas/index.php(21): Zend\Mvc\Application->run()
#18 {main}

```

**Comment by patrickmj** [comment]
This appears to be from modules not handling ACL correctly in their `onBootstrap` methods.
