### ISSUE TITLE
Composer 2 breaks the installation process

### ISSUE THREAD

**Issue by mackensen** [omeka/omeka-s#1659]
Sample output running the install script:

```
npx gulp init
[16:22:07] Using gulpfile /private/tmp/omeka-s/gulpfile.js
[16:22:07] Starting 'init'...
[16:22:07] Starting 'dedist'...
[16:22:07] Finished 'dedist' after 26 ms
[16:22:07] Starting 'deps'...
All settings correct for using Composer
Downloading...

Composer (version 2.0.2) successfully installed to: /private/tmp/omeka-s/build/composer.phar
Use it: php composer.phar

The "dealerdirect/phpcodesniffer-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
You are already using composer version 2.0.2 (stable channel).
The "dealerdirect/phpcodesniffer-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - omeka/composer-addon-installer is locked to version 1.0 and an update of this package was not requested.
    - omeka/composer-addon-installer 1.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 3
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - doctrine/orm v2.7.2 requires ocramius/package-versions ^1.2 -> satisfiable by ocramius/package-versions[1.4.2].
    - doctrine/orm is locked to version v2.7.2 and an update of this package was not requested.

ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
[16:22:09] 'deps' errored after 2.09 s
[16:22:09] Error: Command "php" exited with code 2
    at ChildProcess.<anonymous> (/private/tmp/omeka-s/gulpfile.js:78:28)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:498:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
[16:22:09] 'init' errored after 2.12 s
```
I'm not very familiar with Omeka, but I think the easiest path forward would be updating the gulpfile to stay with the 1.x version of composer for now.

**Comment by zerocrates** [comment]
Hmm yeah. That's certainly an issue.

This feels like the kind of situation where our dependencies will force us to significantly increase our PHP requirement for no particularly compelling reason, but we'll have to see how it shakes out.

For the time being, I think you're definitely right that we should just stick to Composer 1. Existing installations that used version 1 will stay with that version automatically, so we just need to fix the initial install to specify version 1.

**Comment by zerocrates** [comment]
This commit should fix things for the time being.

If you've already got Composer 2 installed, you can just delete the "build" directory and we'll re-install it.

**Comment by Daniel-KM** [comment]
Furthermore, most of living linux distributions on real servers don't have composer 2 pre-packaged.
