### ISSUE TITLE
Logs can't be deleted

### ISSUE THREAD

**Issue by sinanatra** [omeka/omeka-s#1777]
Om my Omeka S version, trying batch delete logs does not do anything. While trying to remove a single log gives an error:

``` 
TypeError:
Return value of Log\Entity\Log::getId() must be of the type int,null returned in /home/project/omeka-s/modules/Log/src/Entity/Log.php:
92 Stack trace:
 #0 /home/project/omeka-s/application/src/Api/Representation/AbstractResourceRepresentation.php(53):
 Log\Entity\Log->getId() #1 /home/project/omeka-s/application/src/Api/Representation/AbstractEntityRepresentation.php(16):
 Omeka\Api\Representation\AbstractResourceRepresentation->__construct() #2 /home/project/omeka-s/application/src/Api/Adapter/AbstractAdapter.php(153):
 Omeka\Api\Representation\AbstractEntityRepresentation->__construct() #3 /home/project/omeka-s/application/src/Api/Manager.php(341):
 Omeka\Api\Adapter\AbstractAdapter->getRepresentation() #4 /home/project/omeka-s/application/src/Api/Manager.php(346):
 Omeka\Api\Manager->Omeka\Api\{closure
}() #5 /home/project/omeka-s/application/src/Api/Manager.php(269):
 Omeka\Api\Manager->finalize() #6 /home/project/omeka-s/application/src/Api/Manager.php(164):
 Omeka\Api\Manager->execute() #7 /home/project/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(189):
 Omeka\Api\Manager->delete() #8 /home/project/omeka-s/modules/Log/src/Controller/Admin/LogController.php(118):
 Omeka\Mvc\Controller\Plugin\Api->delete() #9 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77):
 Log\Controller\Admin\LogController->deleteAction() #10 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321):
 Laminas\Mvc\Controller\AbstractActionController->onDispatch() #11 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178):
 Laminas\EventManager\EventManager->triggerListeners() #12 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103):
 Laminas\EventManager\EventManager->triggerEventUntil() #13 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139):
 Laminas\Mvc\Controller\AbstractController->dispatch() #14 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321):
 Laminas\Mvc\DispatchListener->onDispatch() #15 /home/project/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178):
 Laminas\EventManager\EventManager->triggerListeners() #16 /home/project/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331):
 Laminas\EventManager\EventManager->triggerEventUntil() #17 /home/project/omeka-s/index.php(21):
 Laminas\Mvc\Application->run() #18 {main
}
```

**Comment by sinanatra** [comment]
opened in the module repository: https://github.com/Daniel-KM/Omeka-S-module-Log/issues/7
