### ISSUE TITLE
Need Help getting this error

### ISSUE THREAD

**Issue by jlinsos** [omeka/omeka-s#2199]
Recently migrated to Azure MySql flexible server and getting this error in production, it was working fine before:

Laminas\View\Exception\RuntimeException
Laminas\View\Renderer\PhpRenderer::render: Unable to render template "omeka/install/index"; resolver could not resolve to a file

Details:

Laminas\View\Exception\RuntimeException: Laminas\View\Renderer\PhpRenderer::render: Unable to render template "omeka/install/index"; resolver could not resolve to a file in /home/site/wwwroot/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php:497
Stack trace:
#0 /home/site/wwwroot/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#1 /home/site/wwwroot/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#2 /home/site/wwwroot/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#3 /home/site/wwwroot/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#4 /home/site/wwwroot/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#5 /home/site/wwwroot/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#6 /home/site/wwwroot/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#7 /home/site/wwwroot/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#8 /home/site/wwwroot/index.php(23): Laminas\Mvc\Application->run()
#9 {main}

**Comment by jlinsos** [comment]
nvm, someone had deleted the installer view to prevent it from reinstalling.  thanks.
