### ISSUE TITLE
Strict mode sessions on dev site

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#328]
Trying to use DSpace on our dev site, got this:

Probably related to #327 (and Zend version requirements?)

```
patrickmj@chnmdev scripts]$ php perform-job.php --base-path /websites/omekadev/home/www/omeka-s --job-id 5
PHP Fatal error:  Uncaught exception 'Zend\Session\Exception\InvalidArgumentException' with message ''session.use_strict_mode' is not a valid sessions-related ini setting.' in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/SessionConfig.php:90
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/StandardConfig.php(147): Zend\Session\Config\SessionConfig->setStorageOption('use_strict_mode', true)
#1 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/StandardConfig.php(116): Zend\Session\Config\StandardConfig->setOption('use_strict_mode', true)
#2 /websites/omekadev/home/www/omeka-s/application/Module.php(248): Zend\Session\Config\StandardConfig->setOptions(Array)
#3 /websites/omekadev/home/www/omeka-s/application/Module.php(41): Omeka\Module->configureSession()
#4 [internal function]: Omeka\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
#5 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/Even in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/SessionConfig.php on line 90

Fatal error: Uncaught exception 'Zend\Session\Exception\InvalidArgumentException' with message ''session.use_strict_mode' is not a valid sessions-related ini setting.' in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/SessionConfig.php:90
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/StandardConfig.php(147): Zend\Session\Config\SessionConfig->setStorageOption('use_strict_mode', true)
#1 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/StandardConfig.php(116): Zend\Session\Config\StandardConfig->setOption('use_strict_mode', true)
#2 /websites/omekadev/home/www/omeka-s/application/Module.php(248): Zend\Session\Config\StandardConfig->setOptions(Array)
#3 /websites/omekadev/home/www/omeka-s/application/Module.php(41): Omeka\Module->configureSession()
#4 [internal function]: Omeka\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
#5 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/Even in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-session/src/Config/SessionConfig.php on line 90
```

**Comment by jimsafley** [comment]
`session.use_strict_mode` was only available since PHP 5.5.2.

**Comment by patrickmj** [comment]
yeah,figured it was something like that.  that's what #327 is about. I've emailed Roberto

**Comment by jimsafley** [comment]
We probably need to to up the PHP requirement to `>=5.5.2` in composer.json.

**Comment by rsanc77** [comment]
try 
php55 perform-job.php --base-path /websites/omekadev/home/www/omeka-s --job-id 5

**Comment by patrickmj** [comment]
New local.config.php settings appear to have it running
