### ISSUE TITLE
Error relating item to item, dcterm:relation

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#404]
Building a new item, and using dcterms:relation to connect to another, existing item that HTML media on it, got errors:

```
exception 'Zend\Mvc\Router\Exception\InvalidArgumentException' with message 'Missing parameter "id"' in /var/www/omekas/vendor/zendframework/zend-mvc/src/Router/Http/Segment.php:298
Stack trace:
#0 /var/www/omekas/vendor/zendframework/zend-mvc/src/Router/Http/Segment.php(409): Zend\Mvc\Router\Http\Segment->buildPath(Array, Array, false, false, Array)
#1 /var/www/omekas/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php(330): Zend\Mvc\Router\Http\Segment->assemble(Array, Array)
#2 /var/www/omekas/vendor/zendframework/zend-mvc/src/Router/Http/Part.php(210): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#3 /var/www/omekas/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php(351): Zend\Mvc\Router\Http\Part->assemble(Array, Array)
#4 /var/www/omekas/vendor/zendframework/zend-view/src/Helper/Url.php(100): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#5 /var/www/omekas/modules/MetadataBrowse/Module.php(105): Zend\View\Helper\Url->__invoke(NULL, Array, Array)
#6 [internal function]: MetadataBrowse\Module->repValueHtml(Object(Zend\EventManager\Event))
#7 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\EventManager\Event))
#8 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('rep.value.html', Object(Zend\EventManager\Event), NULL)
#9 /var/www/omekas/application/src/Api/Representation/ValueRepresentation.php(72): Zend\EventManager\EventManager->trigger('rep.value.html', Object(Omeka\Api\Representation\ValueRepresentation), Object(ArrayObject))
#10 /var/www/omekas/application/view-shared/common/resource-values.phtml(28): Omeka\Api\Representation\ValueRepresentation->asHtml()
#11 /var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(501): include('/var/www/omekas...')
#12 /var/www/omekas/vendor/zendframework/zend-view/src/Helper/Partial.php(61): Zend\View\Renderer\PhpRenderer->render('common/resource...', Array)
#13 /var/www/omekas/application/src/Api/Representation/AbstractResourceEntityRepresentation.php(400): Zend\View\Helper\Partial->__invoke('common/resource...', Array)
#14 /var/www/omekas/application/view-admin/omeka/admin/item/show.phtml(31): Omeka\Api\Representation\AbstractResourceEntityRepresentation->displayValues()
#15 /var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(501): include('/var/www/omekas...')
#16 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#17 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#18 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#19 /var/www/omekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#20 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#21 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#22 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#23 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(353): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#24 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(328): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#25 /var/www/omekas/index.php(16): Zend\Mvc\Application->run()
#26 {main}
```

**Comment by zerocrates** [comment]
What page is this happening on? It looks like it's a show page, not an edit.

Anyway, that error's coming from MetadataBrowse, it appears.

**Comment by patrickmj** [comment]
blerg. will address in metadatabrowse
