### ISSUE TITLE
Item won't delete if attached to a site block

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#411]
If an item is attached to a site block, attempting to delete the item from the item/browse or /show view results in the following exceptions. We should either allow the item to be deleted or throw nicer prompts to delete the item from the site block interface first.

```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omekas`.`site_block_attachment`, CONSTRAINT `FK_236473FE126F525E` FOREIGN KEY (`item_id`) REFERENCES `item` (`id`))' in /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#3 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#4 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\Item))
#5 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /Sites/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(356): Doctrine\ORM\EntityManager->flush()
#8 /Sites/omeka-s/application/src/Api/Manager.php(206): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#9 /Sites/omeka-s/application/src/Api/Manager.php(122): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /Sites/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(125): Omeka\Api\Manager->delete('items', '69', Array)
#11 /Sites/omeka-s/application/src/Controller/Admin/ItemController.php(82): Omeka\Mvc\Controller\Plugin\Api->delete('items', '69')
#12 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->deleteAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /Sites/omeka-s/index.php(16): Zend\Mvc\Application->run()
#23 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omekas`.`site_block_attachment`, CONSTRAINT `FK_236473FE126F525E` FOREIGN KEY (`item_id`) REFERENCES `item` (`id`))' in /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#1 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#2 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#3 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\Item))
#4 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /Sites/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(356): Doctrine\ORM\EntityManager->flush()
#7 /Sites/omeka-s/application/src/Api/Manager.php(206): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#8 /Sites/omeka-s/application/src/Api/Manager.php(122): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /Sites/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(125): Omeka\Api\Manager->delete('items', '69', Array)
#10 /Sites/omeka-s/application/src/Controller/Admin/ItemController.php(82): Omeka\Mvc\Controller\Plugin\Api->delete('items', '69')
#11 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->deleteAction()
#12 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /Sites/omeka-s/index.php(16): Zend\Mvc\Application->run()
#22 {main}

Next exception 'Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException' with message 'An exception occurred while executing 'DELETE FROM resource WHERE id = ?' with params [69]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omekas`.`site_block_attachment`, CONSTRAINT `FK_236473FE126F525E` FOREIGN KEY (`item_id`) REFERENCES `item` (`id`))' in /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
Stack trace:
#0 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM res...', Array)
#2 /Sites/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#3 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#4 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\Item))
#5 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /Sites/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /Sites/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(356): Doctrine\ORM\EntityManager->flush()
#8 /Sites/omeka-s/application/src/Api/Manager.php(206): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#9 /Sites/omeka-s/application/src/Api/Manager.php(122): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /Sites/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(125): Omeka\Api\Manager->delete('items', '69', Array)
#11 /Sites/omeka-s/application/src/Controller/Admin/ItemController.php(82): Omeka\Mvc\Controller\Plugin\Api->delete('items', '69')
#12 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->deleteAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /Sites/omeka-s/index.php(16): Zend\Mvc\Application->run()
#23 {main}
```

**Comment by patrickmj** [comment]
Probably duplicate with #382
