### ISSUE TITLE
I18n ExtensionNotLoadedException error

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#489]
When I last pulled from develop, I received the following error when trying to load any page on the admin side while running PHP 5.5.3:

```
exception 'Zend\I18n\Exception\ExtensionNotLoadedException' with message 'Zend\I18n\View\Helper component requires the intl PHP extension' in /Users/kim/Sites/omeka-s/vendor/zendframework/zend-i18n/src/View/Helper/DateFormat.php:50
Stack trace:
#0 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(207): Zend\I18n\View\Helper\DateFormat->__construct()
#1 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(642): Zend\ServiceManager\AbstractPluginManager->createFromInvokable('dateformat', 'dateFormat')
#2 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('dateFormat', 'dateformat')
#3 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#4 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('dateFormat', true)
#5 /Users/kim/Sites/omeka-s/application/src/View/Helper/I18n.php(36): Zend\ServiceManager\AbstractPluginManager->get('dateFormat')
#6 /Users/kim/Sites/omeka-s/application/Module.php(354): Omeka\View\Helper\i18n->__construct(Object(Zend\ServiceManager\ServiceManager))
#7 [internal function]: Omeka\Module->Omeka\{closure}(Object(Zend\View\HelperPluginManager), 'i18n', 'i18n')
#8 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(939): call_user_func(Object(Closure), Object(Zend\View\HelperPluginManager), 'i18n', 'i18n')
#9 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(284): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Object(Closure), 'i18n', 'i18n')
#10 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(244): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Object(Closure), 'i18n', 'i18n')
#11 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\AbstractPluginManager->createFromFactory('i18n', 'i18n')
#12 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('i18n', 'i18n')
#13 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#14 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('i18n', true)
#15 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(372): Zend\ServiceManager\AbstractPluginManager->get('i18n', NULL)
#16 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(390): Zend\View\Renderer\PhpRenderer->plugin('i18n')
#17 /Users/kim/Sites/omeka-s/application/view-admin/omeka/admin/item/browse.phtml(104): Zend\View\Renderer\PhpRenderer->__call('i18n', Array)
#18 /Users/kim/Sites/omeka-s/application/view-admin/omeka/admin/item/browse.phtml(104): Zend\View\Renderer\PhpRenderer->i18n()
#19 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(501): include('/Users/kim/Site...')
#20 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#21 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#22 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#23 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#24 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#25 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#26 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#27 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(353): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#28 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(328): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#29 /Users/kim/Sites/omeka-s/index.php(17): Zend\Mvc\Application->run()
#30 {main}

Next exception 'Zend\ServiceManager\Exception\ServiceNotCreatedException' with message 'An exception was raised while creating "i18n"; no instance returned' in /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:946
Stack trace:
#0 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(284): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Object(Closure), 'i18n', 'i18n')
#1 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(244): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Object(Closure), 'i18n', 'i18n')
#2 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(638): Zend\ServiceManager\AbstractPluginManager->createFromFactory('i18n', 'i18n')
#3 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(598): Zend\ServiceManager\ServiceManager->doCreate('i18n', 'i18n')
#4 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(530): Zend\ServiceManager\ServiceManager->create(Array)
#5 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(116): Zend\ServiceManager\ServiceManager->get('i18n', true)
#6 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(372): Zend\ServiceManager\AbstractPluginManager->get('i18n', NULL)
#7 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(390): Zend\View\Renderer\PhpRenderer->plugin('i18n')
#8 /Users/kim/Sites/omeka-s/application/view-admin/omeka/admin/item/browse.phtml(104): Zend\View\Renderer\PhpRenderer->__call('i18n', Array)
#9 /Users/kim/Sites/omeka-s/application/view-admin/omeka/admin/item/browse.phtml(104): Zend\View\Renderer\PhpRenderer->i18n()
#10 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(501): include('/Users/kim/Site...')
#11 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#12 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#13 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-view/src/View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#14 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#15 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#16 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#17 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#18 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(353): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#19 /Users/kim/Sites/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(328): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#20 /Users/kim/Sites/omeka-s/index.php(17): Zend\Mvc\Application->run()
#21 {main}
```

**Comment by zerocrates** [comment]
Looks like a bug from the UTC changes: you can't even instantiate Zend's date format helper if intl isn't present, so the move of that to the constructor causes this
