### ISSUE TITLE
Site Settings not differentiated by site

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#491]
When site settings have been set for one site, a different site's settings form picks up the same values.

On that second site, when trying to save changes, it gives

```
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'browse_attached_items' for key 'PRIMARY'' in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sit...', Array, Array)
#3 /var/www/omekas/application/src/Settings/SiteSettings.php(51): Doctrine\DBAL\Connection->insert('site_setting', Array, Array)
#4 /var/www/omekas/application/src/Settings/AbstractSettings.php(81): Omeka\Settings\SiteSettings->setSetting('browse_attached...', '0')
#5 /var/www/omekas/application/src/Controller/SiteAdmin/IndexController.php(126): Omeka\Settings\AbstractSettings->set('browse_attached...', '0')
#6 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\SiteAdmin\IndexController->settingsAction()
#7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#17 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'browse_attached_items' for key 'PRIMARY'' in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sit...', Array, Array)
#2 /var/www/omekas/application/src/Settings/SiteSettings.php(51): Doctrine\DBAL\Connection->insert('site_setting', Array, Array)
#3 /var/www/omekas/application/src/Settings/AbstractSettings.php(81): Omeka\Settings\SiteSettings->setSetting('browse_attached...', '0')
#4 /var/www/omekas/application/src/Controller/SiteAdmin/IndexController.php(126): Omeka\Settings\AbstractSettings->set('browse_attached...', '0')
#5 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\SiteAdmin\IndexController->settingsAction()
#6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#8 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#16 {main}

Next exception 'Doctrine\DBAL\Exception\UniqueConstraintViolationException' with message 'An exception occurred while executing 'INSERT INTO site_setting (value, site_id, id) VALUES (?, ?, ?)' with params ["\"0\"", 1, "browse_attached_items"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'browse_attached_items' for key 'PRIMARY'' in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO sit...', Array)
#2 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(696): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO sit...', Array, Array)
#3 /var/www/omekas/application/src/Settings/SiteSettings.php(51): Doctrine\DBAL\Connection->insert('site_setting', Array, Array)
#4 /var/www/omekas/application/src/Settings/AbstractSettings.php(81): Omeka\Settings\SiteSettings->setSetting('browse_attached...', '0')
#5 /var/www/omekas/application/src/Controller/SiteAdmin/IndexController.php(126): Omeka\Settings\AbstractSettings->set('browse_attached...', '0')
#6 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\SiteAdmin\IndexController->settingsAction()
#7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#17 {main}

```

**Comment by zerocrates** [comment]
It may not be that they're not differentiated, but just that the unique index isn't specified correctly.

**Comment by zerocrates** [comment]
That looks to be the case here: the primary key is just id, when it needs to be a composite key of id and site_id.
