### ISSUE TITLE
Site administrators cannot upload media files

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#529]
When trying to upload media (a jpg file), users whose role is "site administrator" receive the following error:

```
exception 'Omeka\Api\Exception\PermissionDeniedException' with message 'Permission denied for the current user to create the Omeka\Entity\Media resource.
                ' in /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php:445
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(388): Omeka\Api\Adapter\AbstractEntityAdapter->authorize(Object(Omeka\Entity\Media), 'create')
#1 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/ItemAdapter.php(187): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#2 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(408): Omeka\Api\Adapter\ItemAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#3 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(336): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#4 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(203): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#5 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(106): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#6 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(110): Omeka\Api\Manager->update('items', '14358', Array, Array, false)
#7 /websites/omekadev/home/www/omeka-s/application/src/Controller/Admin/ItemController.php(154): Omeka\Mvc\Controller\Plugin\Api->update('items', '14358', Array, Array)
#8 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->editAction()
#9 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#14 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#18 /websites/omekadev/home/www/omeka-s/index.php(17): Zend\Mvc\Application->run()
#19 {main}
```

**Comment by zerocrates** [comment]
The site admin role is *explicitly* denied access to create, update, or delete Media.

I can't come up with any reason why this should be the case though. @jimsafley? (this has been part of the site admin's permissions since they were initially created)

**Comment by jimsafley** [comment]
Yeah, I have no idea why I put that in. Fixed now.
