### ISSUE TITLE
Imagick strategy not working on dev

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#592]
On my local install, using Imagick strategy is fine. On dev, though, I get `exception 'Omeka\File\Exception\InvalidThumbnailerException' in /websites/omekadev/home/www/dplafest-omeka-s/application/src/File/Thumbnailer/ImagickThumbnailer.php:19` (details below)

Both have this is in local.config.php

```
    'file_manager' => [
        'thumbnailer' => 'Omeka\File\ImagickThumbnailer',
    ],
```

Trying import with Omeka Importer on both.

On dev dpla site, logged on dev dpla site:

```
2016-04-11T23:30:51+00:00 DEBUG (7): Importing item page 1
2016-04-11T23:31:03+00:00 ERR (3): exception 'Omeka\File\Exception\InvalidThumbnailerException' in /websites/omekadev/home/www/dplafest-omeka-s/application/src/File/Thumbnailer/ImagickThumbnailer.php:19
Stack trace:
#0 /websites/omekadev/home/www/dplafest-omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(1074): Omeka\File\Thumbnailer\ImagickThumbnailer->__construct()
#1 /websites/omekadev/home/www/dplafest-omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(640): Zend\ServiceManager\ServiceManager->createFromInvokable('omekafileimagic...', 'Omeka\\File\\Imag...')
#2 /websites/omekadev/home/www/dplafest-omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(599): Zend\ServiceManager\ServiceManager->doCreate('Omeka\\File\\Imag...', 'omekafileimagic...')
#3 /websites/omekadev/home/www/dplafest-omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(532): Zend\ServiceManager\ServiceManager->create(Array)
#4 /websites/omekadev/home/www/dplafest-omeka-s/application/src/File/Manager.php(61): Zend\ServiceManager\ServiceManager->get('Omeka\\File\\Imag...')
#5 /websites/omekadev/home/www/dplafest-omeka-s/application/src/File/Manager.php(122): Omeka\File\Manager->getThumbnailer()
#6 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Media/Ingester/Url.php(68): Omeka\File\Manager->storeThumbnails(Object(Omeka\File\File))
#7 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Adapter/MediaAdapter.php(154): Omeka\Media\Ingester\Url->ingest(Object(Omeka\Entity\Media), Object(Omeka\Api\Request), Object(Omeka\Stdlib\ErrorStore))
#8 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(404): Omeka\Api\Adapter\MediaAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#9 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Adapter/ItemAdapter.php(187): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#10 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(404): Omeka\Api\Adapter\ItemAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#11 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(287): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#12 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Manager.php(341): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#13 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Manager.php(215): Omeka\Api\Manager->executeBatchCreate(Object(Omeka\Api\Request), Object(Omeka\Api\Adapter\ItemAdapter))
#14 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Api/Manager.php(92): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#15 /websites/omekadev/home/www/dplafest-omeka-s/modules/Omeka2Importer/src/Job/Import.php(233): Omeka\Api\Manager->batchCreate('items', Array, Array, true)
#16 /websites/omekadev/home/www/dplafest-omeka-s/modules/Omeka2Importer/src/Job/Import.php(216): Omeka2Importer\Job\Import->createItems(Array)
#17 /websites/omekadev/home/www/dplafest-omeka-s/modules/Omeka2Importer/src/Job/Import.php(79): Omeka2Importer\Job\Import->importItems(Array)
#18 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Job/Strategy/SynchronousStrategy.php(37): Omeka2Importer\Job\Import->perform()
#19 /websites/omekadev/home/www/dplafest-omeka-s/application/src/Job/Dispatcher.php(102): Omeka\Job\Strategy\SynchronousStrategy->send(Object(Omeka\Entity\Job))
#20 /websites/omekadev/home/www/dplafest-omeka-s/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\Strategy\SynchronousStrategy))
#21 {main}
```

**Comment by patrickmj** [comment]
Plus, direct upload of files seems fine, so maybe a weird thing in the process

**Comment by patrickmj** [comment]
Maybe the PHP5.5 that we have to break out to for cli doesn't have IMagick?

**Comment by zerocrates** [comment]
That's almost certainly the issue.

Can you just take out that part of the local config, so you're using the regular imagemagick thumbnailer?
