### ISSUE TITLE
Sorting items by title throws PDOException 

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#712]
```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'omeka-s.v2_.value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT r0_.id A...')
#1 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SELECT r0_.id A...')
#2 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT r0_.id A...', Array, Array, NULL)
#3 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#5 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#6 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#7 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery->getResult(1)
#8 /var/www/html/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(226): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#9 /var/www/html/omeka-s/application/src/Api/Manager.php(209): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#10 /var/www/html/omeka-s/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#11 /var/www/html/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(49): Omeka\Api\Manager->search('items', Array)
#12 /var/www/html/omeka-s/application/src/Controller/Admin/ItemController.php(36): Omeka\Mvc\Controller\Plugin\Api->search('items', Array)
#13 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->browseAction()
#14 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#18 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#19 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#21 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#23 /var/www/html/omeka-s/index.php(17): Zend\Mvc\Application->run()
#24 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'omeka-s.v2_.value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
Stack trace:
#0 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SELECT r0_.id A...')
#1 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT r0_.id A...', Array, Array, NULL)
#2 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#3 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#4 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#5 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#6 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery->getResult(1)
#7 /var/www/html/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(226): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#8 /var/www/html/omeka-s/application/src/Api/Manager.php(209): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#9 /var/www/html/omeka-s/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /var/www/html/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(49): Omeka\Api\Manager->search('items', Array)
#11 /var/www/html/omeka-s/application/src/Controller/Admin/ItemController.php(36): Omeka\Mvc\Controller\Plugin\Api->search('items', Array)
#12 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->browseAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#17 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#22 /var/www/html/omeka-s/index.php(17): Zend\Mvc\Application->run()
#23 {main}

Next Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT r0_.id AS id_0, r0_.is_public AS is_public_1, r0_.created AS created_2, r0_.modified AS modified_3, r0_.resource_type AS resource_type_4, r0_.owner_id AS owner_id_5, r0_.resource_class_id AS resource_class_id_6, r0_.resource_template_id AS resource_template_id_7 FROM item i1_ INNER JOIN resource r0_ ON i1_.id = r0_.id LEFT JOIN value v2_ ON r0_.id = v2_.resource_id AND (v2_.property_id = 1) GROUP BY r0_.id ORDER BY v2_.value ASC, r0_.id ASC LIMIT 25 OFFSET 0':

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'omeka-s.v2_.value' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Stack trace:
#0 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/html/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT r0_.id A...', Array)
#2 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT r0_.id A...', Array, Array, NULL)
#3 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#5 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#6 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#7 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery->getResult(1)
#8 /var/www/html/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(226): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#9 /var/www/html/omeka-s/application/src/Api/Manager.php(209): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#10 /var/www/html/omeka-s/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#11 /var/www/html/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(49): Omeka\Api\Manager->search('items', Array)
#12 /var/www/html/omeka-s/application/src/Controller/Admin/ItemController.php(36): Omeka\Mvc\Controller\Plugin\Api->search('items', Array)
#13 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->browseAction()
#14 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#18 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(118): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#19 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#20 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#21 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#23 /var/www/html/omeka-s/index.php(17): Zend\Mvc\Application->run()
#24 {main}
```

**Comment by jimsafley** [comment]
The DQL:

```
SELECT Omeka\Entity\Item 
FROM Omeka\Entity\Item Omeka\Entity\Item 
LEFT JOIN Omeka\Entity\Item.values omeka_0 WITH omeka_0.property = 1 
GROUP BY Omeka\Entity\Item.id 
ORDER BY omeka_0.value DESC, Omeka\Entity\Item.id DESC
```

The SQL:

```
SELECT r0_.id AS id_0, r0_.is_public AS is_public_1, r0_.created AS created_2, r0_.modified AS modified_3, r0_.resource_type AS resource_type_4, r0_.owner_id AS owner_id_5, r0_.resource_class_id AS resource_class_id_6, r0_.resource_template_id AS resource_template_id_7 
FROM item i1_ 
INNER JOIN resource r0_ ON i1_.id = r0_.id 
LEFT JOIN value v2_ ON r0_.id = v2_.resource_id AND (v2_.property_id = 1) 
GROUP BY r0_.id 
ORDER BY v2_.value DESC, r0_.id DESC
```

The `ONLY_FULL_GROUP_BY` SQL mode was added in MySQL 5.7.5.

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by
http://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

**Comment by jimsafley** [comment]
Adding `$qb->addGroupBy("$valuesAlias.id");` to the property part of `AbstractResourceEntityAdapter::sortQuery()` seems to fix it, but not entirely sure why. It makes sense that the `ONLY_FULL_GROUP_BY` restriction would require the additional `GROUP BY` but I'm not sure why other, similar, sorting queries don't.

For example, the query to sort by "Owner" also has an `ORDER BY` that's not named in the `GROUP BY` clause, but it works without using `addGroupBy()`. Maybe it's because that particular `ORDER BY` is "functionally dependent on (uniquely determined by)" the `GROUP BY` column. The one difference I see is the `WITH` condition on the `LEFT JOIN` when sorting by property. I don't know.

What do you think, @zerocrates?

**Comment by zerocrates** [comment]
Yes, this is a MySQL 5.7 thing, see also omeka/Omeka#684

> Adding $qb->addGroupBy("$valuesAlias.id"); to the property part of AbstractResourceEntityAdapter::sortQuery() seems to fix it

I would suspect this actually breaks it, at least in the case where some items have multiple values of the property you're sorting by. You'd end up with duplicate or at least incorrectly paginated results, as that's what adding additional GROUP BY's does: it splits things into more groups, so you'd have multiple result rows for the same item.

> For example, the query to sort by "Owner" also has an ORDER BY that's not named in the GROUP BY clause, but it works without using addGroupBy(). Maybe it's because that particular ORDER BY is "functionally dependent on (uniquely determined by)" the GROUP BY column.

Sort of... more or less the idea is that an item doesn't have (and can't have) multiple owners, so there's no ambiguity on which value MySQL should use to sort the row. When we group by the ID, all the columns of the same table or one-to-one joined tables are functionally dependent on the ID.

This should be solvable without _too_ much trouble with a subquery (which I've noodled around with for classic as well, but haven't had time to really focus on; the current frontrunner "solution" there is just removing the ONLY_FULL_GROUP_BY mode). The question for us here would be whether a "weird" query like that can be represented in DQL.
