### ISSUE TITLE
Dev S installs throwing error after last pull

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#733]
I've updated both the shared S install and my dev install (on the dev server) to the latest commit. Both are throwing errors this morning:

On http://dev.omeka.org/omeka-s/admin (which is on commit fc41ffe6407022b69d4b75a3490ee5a146751dbc 
```
Zend\EventManager\Exception\InvalidArgumentException
Invalid identifier provided; must be a string; received "array"

Details:

exception 'Zend\EventManager\Exception\InvalidArgumentException' with message 'Invalid identifier provided; must be a string; received "array"' in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/SharedEventManager.php:64
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/modules/Sharing/Module.php(38): Zend\EventManager\SharedEventManager->attach(Array, 'view.show.after', Array)
#1 /websites/omekadev/home/www/omeka-s/application/src/Module/AbstractModule.php(35): Sharing\Module->attachListeners(Object(Zend\EventManager\SharedEventManager))
#2 /websites/omekadev/home/www/omeka-s/modules/Sharing/Module.php(18): Omeka\Module\AbstractModule->onBootstrap(Object(Zend\Mvc\MvcEvent))
#3 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Sharing\Module->onBootstrap(Object(Zend\Mvc\MvcEvent))
#4 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#5 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(161): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#6 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Application.php(40): Zend\Mvc\Application->bootstrap(Array)
#7 /websites/omekadev/home/www/omeka-s/index.php(17): Omeka\Mvc\Application::init(Array)
#8 {main}
```

On http://dev.omeka.org/mebrett/testomekas/admin (commit fc41ffe6407022b69d4b75a3490ee5a146751dbc )

```
Zend\EventManager\Exception\InvalidArgumentException
Invalid event provided; must be a non-empty string; received "array"

Details:

exception 'Zend\EventManager\Exception\InvalidArgumentException' with message 'Invalid event provided; must be a non-empty string; received "array"' in /websites/omekadev/home/www/mebrett/testomekas/vendor/zendframework/zend-eventmanager/src/SharedEventManager.php:71
```

I ran ant install-deps (the whole long string thing from slack) on both after pulling.

**Comment by kimisgold** [comment]
Looks like the dependencies didn't properly install because the dev server is using PHP 5.4.44 and we're requiring 5.6.

```
install-deps:
     [exec] Loading composer repositories with package information
     [exec] Installing dependencies (including require-dev) from lock file
     [exec] Your requirements could not be resolved to an installable set of packages.
     [exec] 
     [exec]   Problem 1
     [exec]     - This package requires php >=5.6 but your PHP version (5.4.44) does not satisfy that requirement.
     [exec]   Problem 2
     [exec]     - zendframework/zend-i18n-resources 2.5.2 requires php >=5.5 -> your PHP version (5.4.44) does not satisfy that requirement.
     [exec]     - zendframework/zend-i18n-resources 2.5.2 requires php >=5.5 -> your PHP version (5.4.44) does not satisfy that requirement.
     [exec]     - Installation request for zendframework/zend-i18n-resources 2.5.2 -> satisfiable by zendframework/zend-i18n-resources[2.5.2].
     [exec] 
```

**Comment by mebrett** [comment]
I ran `ant -Dphp.path=/opt/php5.6/bin/php install-deps`

**Comment by kimisgold** [comment]
I missed that, my bad.

**Comment by kimisgold** [comment]
Looks like it was a problem with the Sharing module. Pulling its latest commits seems to have fixed it.

**Comment by patrickmj** [comment]
@mebrett Generally, all the modules will need updates due to the core upgrade to ZF3. I'm pretty sure that the ZF3 breakiness has been fixed in them all. So, if any other modules are there but not installed or active, update all those, too, and let us know if one causes similar problems.
