### ISSUE TITLE
TypeError with "phar" extension

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#758]
Getting the following TypeError when navigating to `admin/media/:id` for a file with a "phar" extension (php-cs-fixer.phar):

```
TypeError: Phar::__construct() expects at least 1 parameter, 0 given in /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php:32
Stack trace:
#0 /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php(32): Phar->__construct()
#1 /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(747): Zend\ServiceManager\Factory\InvokableFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'phar', NULL)
#2 /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(195): Zend\ServiceManager\ServiceManager->doCreate('phar')
#3 /var/www/html/omeka-s/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(143): Zend\ServiceManager\ServiceManager->get('phar')
#4 /var/www/html/omeka-s/application/src/Media/Renderer/File.php(34): Zend\ServiceManager\AbstractPluginManager->get('phar')
#5 /var/www/html/omeka-s/application/src/View/Helper/Media.php(115): Omeka\Media\Renderer\File->render(Object(Zend\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\MediaRepresentation), Array)
#6 /var/www/html/omeka-s/application/src/Api/Representation/MediaRepresentation.php(49): Omeka\View\Helper\Media->render(Object(Omeka\Api\Representation\MediaRepresentation), Array)
#7 /var/www/html/omeka-s/application/view-admin/omeka/admin/media/show.phtml(15): Omeka\Api\Representation\MediaRepresentation->render()
#8 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(502): include('/var/www/html/o...')
#9 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render()
#10 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#11 /var/www/html/omeka-s/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#12 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#13 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#14 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#15 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#16 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#17 /var/www/html/omeka-s/index.php(17): Zend\Mvc\Application->run()
#18 {main}
```

**Comment by zerocrates** [comment]
ugh okay gotta turn off auto-invokable there

**Comment by zerocrates** [comment]
and potentially in all the other custom managers, or at least most of them

**Comment by zerocrates** [comment]
```
protected $autoAddInvokableClass = false;
```

in Media\FileRenderer\Manager should fix this.

**Comment by zerocrates** [comment]
But in general any of these places where we take user input and compare to our list of registered services needs the same treatment: otherwise remote users can instantiate arbitrary classes at will
