### ISSUE TITLE
Error on api-context route

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#799]
Omeka\Event\Event doesn't exist anymore.

```
Error: Class 'Omeka\Event\Event' not found in /var/www/html/omeka-s/application/src/Controller/ApiController.php:49
Stack trace:
#0 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(345): Omeka\Controller\ApiController->contextAction()
#1 /var/www/html/omeka-s/application/src/Controller/ApiController.php(164): Zend\Mvc\Controller\AbstractRestfulController->onDispatch(Object(Zend\Mvc\MvcEvent))
#2 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Omeka\Controller\ApiController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#4 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#5 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractRestfulController.php(313): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#6 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractRestfulController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#9 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/omeka-s/index.php(17): Zend\Mvc\Application->run()
#11 {main}
```

**Comment by patrickmj** [comment]
Should be a super-easy fix, but I'm confused about how to reproduce it so I can check the fix.

**Comment by zerocrates** [comment]
your-site/api-context

**Comment by patrickmj** [comment]
thanks. route names and the url that goes with them still confuse me here and there.

While I'm in there, do the paginator and logger helpers now apply there like in other controllers, so those properties should be updated?

**Comment by zerocrates** [comment]
Yes, those should be equally applicable there.

**Comment by patrickmj** [comment]
hmm....something seems amiss in lining up the usages. Property-style `$this->paginator()` returns null, I guess because of a silent error because the params aren't passed to the paginator as they are elsewhere with `$this->paginator($response->getTotalResults(), $this->params()->fromQuery('page'));`?

That means I can't change 
```php
$this->paginator->getPreviousPage()
```

```php
$this->paginator()->getPreviousPage()
```

New issue, or am I missing something (or both).

**Comment by zerocrates** [comment]
I think the paginator plugin isn't actually applicable: it uses the paginator view helper internally and here we're not interested in setting stuff up for the view helpers.

$this->paginator() in a controller always returns null, because it's only concerned with setting stuff.

**Comment by patrickmj** [comment]
ok, thanks. no changes to paginator in there, then.
