### ISSUE TITLE
api-context route not working

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#804]
The response contains an empty array. All modules are uninstalled.

**Comment by zerocrates** [comment]
This is the same mistake that's been made nearly everywhere possible: `Event:API_CONTEXT`'s original value was `api.context`, not `api_context`.

**Comment by zerocrates** [comment]
We will have now fixed the api-context action 3 times in the past 3 weeks. It's probably worth it at this point to have some test coverage in this area.

**Comment by patrickmj** [comment]
Here's what I got from `grep -r api.context .` at my base install. I think all modules and code are up to date.

```
./application/Module.php:            'api.context',
./application/src/Api/Representation/AbstractResourceRepresentation.php:                '@context' => $url('api-context', [], ['force_canonical' => true]),
./application/src/Controller/ApiController.php:        $eventManager->triggerEvent(new MvcEvent('api.context', null, $args));
./application/config/routes.config.php:            'api-context' => [
./application/config/routes.config.php:                    'route' => '/api-context',
./modules/Collecting/Module.php:            'api.context',
./modules/Mapping/Module.php:            'api.context',
./logs/application.log:2016-11-05T18:21:49+00:00 ERR (3): Omeka\Api\Exception\BadRequestException: The API does not support the "api-context" resource. in /var/www/omekas/application/src/Api/Manager.php:180
./logs/application.log:#1 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(49): Omeka\Api\Manager->search('api-context', Array)
./logs/application.log:#2 /var/www/omekas/application/src/Controller/ApiController.php(71): Omeka\Mvc\Controller\Plugin\Api->search('api-context', Array)



```
