### ISSUE TITLE
Error when uploading file to item

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#820]
Hi,

I have an error message when trying to upload a file to a item (using media tab when editing a item).

See log below. My configuration is Omeka S 1.0.0-beta, php 5.6.5, mariadb 5.5.50.

It seems Omeka S doesn't include Zend framework unlike Omeka classic. If it is indeed the case, it should be probably added as dependence.
 
P-S: Do you prefer bug report like this one be posted on Github or Omeka forum?

```
exception 'Zend\Filter\Exception\InvalidArgumentException' with message 'Invalid target, must be a string' in /data/www/myserver/public/omeka-s/vendor/zendframework/zend-filter/src/File/RenameUpload.php:59
Stack trace:
#0 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-filter/src/AbstractFilter.php(51): Zend\Filter\File\RenameUpload->setTarget(false)
#1 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-filter/src/File/RenameUpload.php(46): Zend\Filter\AbstractFilter->setOptions(Array)
#2 /data/www/myserver/public/omeka-s/application/src/Media/Ingester/Upload.php(72): Zend\Filter\File\RenameUpload->__construct(Array)
#3 /data/www/myserver/public/omeka-s/application/src/Api/Adapter/MediaAdapter.php(154): Omeka\Media\Ingester\Upload->ingest(Object(Omeka\Entity\Media), Object(Omeka\Api\Request), Object(Omeka\Stdlib\ErrorStore))
#4 /data/www/myserver/public/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(418): Omeka\Api\Adapter\MediaAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#5 /data/www/myserver/public/omeka-s/application/src/Api/Adapter/ItemAdapter.php(206): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Media), Object(Omeka\Stdlib\ErrorStore))
#6 /data/www/myserver/public/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(418): Omeka\Api\Adapter\ItemAdapter->hydrate(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#7 /data/www/myserver/public/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(333): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#8 /data/www/myserver/public/omeka-s/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#9 /data/www/myserver/public/omeka-s/application/src/Api/Manager.php(129): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /data/www/myserver/public/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(132): Omeka\Api\Manager->update('items', '1', Array, Array, false)
#11 /data/www/myserver/public/omeka-s/application/src/Controller/Admin/ItemController.php(176): Omeka\Mvc\Controller\Plugin\Api->update('items', '1', Array, Array)
#12 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemController->editAction()
#13 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#16 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /data/www/myserver/public/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#20 /data/www/myserver/public/omeka-s/index.php(17): Zend\Mvc\Application->run()
#21 {main}
```

**Comment by patrickmj** [comment]
This looks like ZF is indeed there -- otherwise, it would have failed much earlier in the trace. More likely is that Omeka S can't read PHP's temporary file path. Is that readable by the server?

Unless other developers chime in, I think we're happy with bug reports in either place, at least for now.

**Comment by pprw** [comment]
Thank for the answer.

The whole Omeka S folder has a 750 permission. Could you indicate me if a specific folder needs more than 750?

**Comment by patrickmj** [comment]
If my guess about what the issue is is correct, you'll need to check the system's temporary directory, often something like `/tmp`, to make sure PHP can read and write to it.

**Comment by pprw** [comment]
The error was fixed by adding permissions to /tmp, indeed. Thanks patrickmj!
